Brainstrom/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('user/', include('account.urls')),
    path('quiz/', include('quiz.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('leaderboard', views.leaderboard_view, name='leaderboard'),
]

quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('all_quiz', views.all_quiz_view, name='all_quiz'),
     path('search/<str:category>', views.search_view, name='search'),
     path('<int:quiz_id>', views.quiz_view, name='quiz'),
]

quiz/models.py
from django.db import models
import pandas as pd
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=15)

    class Meta:
        verbose_name_plural = 'Categories'
        
    def __str__(self):
        return self.name
        
class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    quiz_file = models.FileField(upload_to='quiz/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Quizzes'
    
    def __str__(self):
        return self.title
    
     # call the function on quiz save
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.quiz_file:
            self.import_quiz_from_excel()

    # function to extract excel file
    def import_quiz_from_excel(self):
        # read teh excel file
        df = pd.read_excel(self.quiz_file.path)

         # iterate over the each row
        for index, row in df.iterrows():
            # extract question text, choices and correct answer from the row
            question_text = row['Question']
            choice1 = row['A']
            choice2 = row['B']
            choice3 = row['C']
            choice4 = row['D']
            correct_answer = row['Answer']

            # create the question object
            question = Question.objects.get_or_create(quiz=self, text=question_text)

            # create choices objects
            choice_1 = Choice.objects.get_or_create(question=question[0], text=choice1, is_correct=correct_answer == 'A')
            choice_2 = Choice.objects.get_or_create(question=question[0], text=choice2, is_correct=correct_answer == 'B')
            choice_3 = Choice.objects.get_or_create(question=question[0], text=choice3, is_correct=correct_answer == 'C')
            choice_4 = Choice.objects.get_or_create(question=question[0], text=choice4, is_correct=correct_answer == 'D')

    
class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text[:50]
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.question.text[:50]}, {self.text[:20]}"
    

class QuizSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}, {self.quiz.title}"
    
class UserRank(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rank = models.IntegerField(null=True, blank=True)
    total_score = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.rank}, {self.user.username}"
    
@receiver(post_save, sender=QuizSubmission)
def update_leaderboard(sender, instance, created, **kwargs):
    if created:
        update_leaderboard()



def update_leaderboard():
    # Count the sum of scores for all users
    user_scores = (QuizSubmission.objects.values('user').annotate(total_score=Sum('score')).order_by('-total_score'))

    # Update rank based on the sorted list
    rank = 1
    for entry in user_scores:
        user_id = entry['user']
        total_score = entry['total_score']

        user_rank, created = UserRank.objects.get_or_create(user_id=user_id)
        user_rank.rank = rank
        user_rank.total_score = total_score
        user_rank.save()

        rank += 1

quiz/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from account.models import Profile
from .models import Quiz, Category
from django.db.models import Q
from quiz.models import QuizSubmission
from django.contrib import messages

# Create your views here.

@login_required(login_url='login')
def all_quiz_view(request):
    
    user_object = User.objects.get(username=request.user)
    user_profile = Profile.objects.get(user=user_object)
    
    quizzes = Quiz.objects.order_by('-created_at')
    categories = Category.objects.all()
    
    context = {"user_profile": user_profile, "quizzes": quizzes, "categories": categories}
    return render(request, 'all_quiz.html', context)

@login_required(login_url='login')
def search_view(request,category):
    
    user_object = User.objects.get(username=request.user)
    user_profile = Profile.objects.get(user=user_object)
    
    # search by search bar
    if request.GET.get('q') != None:
        q = request.GET.get('q')
        query = Q(title__icontains=q) | Q(description__icontains=q)
        quizzes = Quiz.objects.filter(query).order_by('-created_at')
    # search by category
    elif category !=" ":
        quizzes = Quiz.objects.filter(category__name=category).order_by('-created_at')
        
    
    else:    
        quizzes = Quiz.objects.order_by('-created_at')
        
    categories = Category.objects.all()
    
    context = {"user_profile": user_profile, "quizzes": quizzes, "categories": categories}
    return render(request, 'all_quiz.html', context)

@login_required(login_url='login')
def quiz_view(request, quiz_id):
    
    user_object = User.objects.get(username=request.user)
    user_profile = Profile.objects.get(user=user_object)
    
    quiz = Quiz.objects.filter(id=quiz_id).first()
    
    total_questions = quiz.question_set.all().count()

    if request.method == "POST":
        
        # Get the score
        score = int(request.POST.get('score', 0))

        # Check if the user has already submiited the quiz
        if QuizSubmission.objects.filter(user=request.user, quiz=quiz).exists():
            messages.success(request, f"This time you got {score} out of {total_questions}")
            return redirect('quiz', quiz_id)
        
        # save the new quiz submission
        submission = QuizSubmission(user=request.user, quiz=quiz, score=score)
        submission.save()

        # show the result in message
        messages.success(request,f"Quiz Submitted Successfully. You got {score} out of {total_questions}")
        return redirect('quiz', quiz_id)

    
    if quiz != None:
        context = {"user_profile": user_profile, "quiz": quiz}
    else:
        return redirect('all_quiz')
    return render(request, 'quiz.html', context)

templates/all_quiz.html
{% extends "index.html" %}

{% block title %} All Quizzes - BrainStrom{% endblock title %}

{% block content %}
    <h1 class="text-center display-4 my-5">All Quizzes</h1>

    <div class="container">
      <div class="d-flex flex-wrap">
        <a href="{% url 'all_quiz' %}"  class="btn btn-sm btn-light m-1">All Quiz</a>
        {% for category in categories %}
        <a href="{% url 'search' category.name %}"  class="btn btn-sm btn-light m-1">{{category.name}}</a>
        {% endfor %}
      </div>
    </div>
    <form class="container d-flex my-4" role="search" method="get" action="{% url 'search' ' ' %}" >
      <input  name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <a href="#" type="submit" class="btn btn-primary ms-2">Search</a>
    </form>
    
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 g-3">
        {% if quizzes|length > 0 %}
        {% for quiz in quizzes %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <h4>{{quiz.title}}</h4>
              <p class="card-text">Total Questions - {{quiz.question_set.all|length}}</p>
              <p class="card-text"> {{quiz.description|truncatewords:7}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'quiz' quiz.id %}" type="button" class="btn btn-sm btn-outline-success">Start Quiz</a>
                </div>
                <small class="text-body-secondary">{{quiz.created_at|timesince}} ago</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
			<div class="col-lg-12 col-md-12 col-12">
				<p class="text-center text-danger fs-5">There is no quiz available for this category or search.</p>
			</div>
			{% endif %}
      </div>
    </div>


   {% endblock content %}

templates/confirm.html
{% extends 'index.html' %}

{% block title %} {{request.user.username}} Profile Delete Confirmation - BrainStrom{% endblock title %}


{% block content %}
  <h1 class="display-4 text-center my-5">Confirmation Page</h1>

  <div class="container">
    <form action="" method="POST" class="">
        {% csrf_token %}
        <p class="fs-4"><b>@{{request.user.username}}</b>, Are you sure you want to delete your profile??</p>
        <a href="{% url 'profile' request.user.username %}" class="btn btn-success" type="button">Back to Profile</a>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
  </div>
{% endblock content %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Welcome to BrainStrom{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" integrity="sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% include "components/navbar.html" %}

     {% block content %}
     
     {% endblock content %}

    {% include "components/footer.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
</body>
</html>

templates/leaderboard.html
{% extends 'index.html'%}
{% block title %}Leaderboard - BrainStrom{% endblock title %}
{% block content %}

    <div class="container text-center">
        <h1 class="text-center display-4 my-5">Leaderboard</h1>

        <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 mx-3">
          {% if leaderboard_users|length == 0 %}
          <div class="col-lg-4 position-relative mb-4">
              <h4 class="text-center text-danger">No User Available on Leaderboard!!</h4>
          </div>
          {% else %} 
          {% for rank in leaderboard_users %}
          <div class="col-lg-4 position-relative mb-4">
            <img src="{{rank.user.profile.profile_img.url}}" class="rounded-circle" width="150" height="150" alt="user-profile">
            <span class="position-absolute top-0 start-90 translate-middle badge rounded-pill bg-success">{{forloop.counter}}</span>
            <h2 class="fw-normal">@{{rank.user.username}}</h2>
            <p>{{rank.user.profile.bio|truncatewords:5}}</p>
            <p><a class="btn btn-secondary" href="{% url 'profile' rank.user.username  %}">View Profile »</a></p>
          </div>
          {% endfor %}
          {% endif %}
          </div>
    </div>
    
    {% endblock content %}

templates/login.html
{% extends "index.html" %}

{% block title %} Login Page - BrainStrom{% endblock title %}

{% block content %}
      <h1 class="text-center display-4 my-5">Login</h1>

      <div class="container">
        <div class="row row-cols-sm-1 row-cols-lg-3 container">
            <div class="col-12">
              </div>
              <div class="col-12">
                <div>
                  {% if messages %}
                    <ul class="messages">
                     {% for message in messages %}
                        <li>{{ message }}</li>
                     {% endfor %}
                   </ul>
                  {% endif %}
                </div>
                <form method="POST" action="">
                 {% csrf_token %}
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label visually-hidden">Username</label>
                      <input type="username" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username"required>
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label visually-hidden">Password</label>
                      <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
                    </div>
                    <div class="mb-3 form-check">
                      <input type="checkbox" class="form-check-input" id="exampleCheck1">
                      <label class="form-check-label" for="exampleCheck1">Remember me</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                  </form>
                  <p>Not a user?<a href="{% url 'register' %}">Register</a></p>
              </div>
              <div class="col-12">
              </div>
      </div>

{% endblock content %}

templates/profile-edit.html
{% extends 'index.html' %}

{% block title %} {{request.user.username}} Profile Edit - BrainStrom{% endblock title %}


{% block content %}

  <h1 class="display-4 text-center my-5">Edit Profile</h1>


  <div class="container">
    <div class="row row-cols-sm-1 row-cols-lg-3 container">
      <div class="col-12">
      </div>
      <div class="col-12">

        

        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 d-flex justify-content-center">
                <img src="{{user_profile.profile_img.url}}" alt="profile-pic" width="150" height="150" class="rounded-circle">
            </div>

            <div class="mb-3">
                {% for message in messages %}
                <h5 class="text-danger">{{message}}</h5>
                {% endfor %}
              </div>

            <div class="mb-3">
                <label for="exampleInputImage" class="form-label visually-hidden">Profile Image</label>
                <input type="file" name="profile_img" class="form-control" id="exampleInputImage">
              </div>
              <div class="mb-3">
                <label for="exampleInputFirstName" class="form-label visually-hidden">First Name</label>
                <input type="text" name="firstname" value="{{user_profile.user.first_name}}" class="form-control" id="exampleInputFirstName" placeholder="First Name" required>
              </div>
              <div class="mb-3">
                <label for="exampleInputLastName" class="form-label visually-hidden">Last Name</label>
                <input type="text" name="lastname" value="{{user_profile.user.last_name}}" class="form-control" id="exampleInputLastName" placeholder="Last Name" required>
              </div>
              <div class="mb-3">
                <label for="exampleInputEmail2" class="form-label visually-hidden">Email</label>
                <input type="email" name="email" value="{{user_profile.user.email}}" class="form-control" id="exampleInputEmail2" aria-describedby="emailHelp"
                  placeholder="Email" required>
              </div>
              <div class="mb-3">
                <label for="exampleInputUsername1" class="form-label visually-hidden">Username</label>
                <input type="text" name="username" value="{{user_profile.user.username}}" class="form-control" id="exampleInputUsername1" aria-describedby="emailHelp"
                  placeholder="Username" required>
              </div>
              <div class="mb-3">
                <label for="exampleInputLocation" class="form-label visually-hidden">Location</label>
                <input type="text" name="location" value="{{user_profile.location}}" class="form-control" id="exampleInputLocation" placeholder="Location" required>
              </div>
          
              <div class="mb-3">
                <label for="exampleInputGender" class="form-label visually-hidden">Gender</label>
                <select class="form-select form-control" name="gender" id="exampleInputGender" aria-label="Default select example" required>
                    <option selected>Choose Your Gender</option>
                    <option {% if user_profile.gender == 'Male' %}selected{% endif %} value="Male">Male</option>
                    <option {% if user_profile.gender == 'Female' %}selected{% endif %} value="Female">Female</option>
                    <option {% if user_profile.gender == 'Other' %}selected{% endif %} value="Other">Other</option>
                  </select>
              </div>

          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label visually-hidden">Your Bio</label>
            <textarea class="form-control" name="bio" id="exampleFormControlTextarea1" rows="3" placeholder="Your Bio" required>{{user_profile.bio}}</textarea>
          </div>

          <button type="submit" class="btn btn-success">Save Profile</button>
        </form>
      </div>
      <div class="col-12">
      </div>
    </div>
  </div>


  {% endblock content %}

templates/profile.html
{% extends 'index.html' %}

{% block title %} {{user_profile2.user.username}}'s Profile - BrainStrom{% endblock title %}


{% block content %}

      <h1 class="text-center display-4 my-5">{{user_profile2.user.username}}'s Profile</h1>
    <div class="container text-center">
        {% if request.user.username == user_profile2.user.username %}
        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <a href="{% url 'edit_profile' %}" type="button" class="btn btn-outline-primary">Edit</a>
            <a href="{% url 'delete_profile' %}" type="button" class="btn btn-outline-danger">Delete</a>
          </div>
          {% endif %}

          <div class="container text-center my-4">
            <div class="row row-cols-sm-1 row-cols-md-2">
              <div class="col-12">
                <img src="{{user_profile2.profile_img.url}}" alt="user-profile" width="170" height="150" class="rounded-circle">
                <h2 class="fs-3">{{user_profile2.user.username}}</h2>
              </div>
              <div class="col-12">
                <h2>{{user_profile2.user.first_name|default:"Full Name Not Available"}} {{user_profile2.user.last_name}}</h2>
                <p class="fs-5"><i class="bi bi-gender-ambiguous"></i>{{user_profile2.gender|default:"Gender Not Available"}}</p>
                <p class="fs-5"><i class="bi bi-geo-alt-fill"></i>{{user_profile2.location|default:"Location Not Available"}}</p>
                <p class="fs-5"><i class="bi bi-file-person"></i>{{user_profile2.bio|default:"Bio Not Available"}}</p>
                {% if request.user.is_superuser %}
                <p class="fs-5"><i class="bi bi-envelope-at"></i> <a href="mailto:{{user_profile2.user.email}}"> {{user_profile2.user.email|default:'Email Not Available'}}</a></p>
                {% endif %}
              </div>
            </div>
          </div>
          <hr class="my-5">

          <div class="container">
            <div class="row row-cols-sm-1 row-cols-md-1 row-cols-lg-1">
                <div class="col-12">
                    <h3>Quiz attended by {{user_profile2.user.username}}</h3>
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Quiz</th>
                            <th scope="col">Mark</th>
                            <th scope="col">Time</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for submission in submissions %}
                          <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td title="{{submission.quiz.title}}">{{submission.quiz.title|truncatewords:4}}</td>
                            <td>{{submission.score}}/{{submission.quiz.question_set.all|length}}</td>
                            <td>{{submission.submitted_at|timesince}} ago</td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                </div>
                {% comment %} <div class="col">
                  <h3>{{user_profile2.user.username}}'s Performance</h3>
                </div> {% endcomment %}
              </div>
            
          </div>
    </div>

 {% endblock content %}

templates/quiz.html
{% extends 'index.html' %}

{% block title %} {{quiz.title}} - BrainBunny{% endblock title %}

{% block content %}
<h1 class="display-4 text-center my-5">{{quiz.title}} - ({{quiz.question_set.all|length}})</h1>
      <p class="fs-4 text-center container">{{quiz.description}}</p>
    
      <div class="container">
        <div class="d-flex justify-content-between">
            <span class="fs-5">{{quiz.created_at}}</span>
            <span class="fs-5" id="timer">10:00PM</span>
        </div>

        {% for message in messages %}
        <div id="message-div">
            <h4 class="text-center text-success">{{message}}</h4>
        </div>
        {% endfor %}

        <div class="questions my-4">
          {% for question in quiz.question_set.all %}
            <div class="card mb-2 question">
                <div class="card-header fw-bold">
                  Question {{forloop.counter}}
                </div>
                <div class="card-body">
                    <p class="card-text">{{question.text}}</p>
                {% for option in question.choice_set.all %}
                <div class="form-check">
                    <label class="form-check-label" for="{{option.id}}">
                        <input class="form-check-input" value="{{option.text}}" type="radio" name="{{option.question.id}}" id="{{option.id}}">
                        {{option.text}}
                    </label>
                    {% if option.is_correct %}
                        <span class="visually-hidden correct-answer">{{option.text}}</span>
                    {% endif %}
                  </div>
                  {% endfor%}
              </div>
            </div>
            {% endfor %}
        </div>


        <form action="" method="post" id="quiz-form">
          {% csrf_token %}
          <!-- hidden input field for score -->
          <input type="hidden" name="score" value="0" id="user-score">

          <!-- submit button -->
          <button type="submit" class="btn btn-primary" id="submit-button">Submit the quiz</button>
      </form>
      </div>

      <script>
        // Elements
        var submitButton = document.getElementById("submit-button");
        var timerSpan = document.getElementById("timer");
        var quizForm = document.getElementById("quiz-form");
        var questions = document.querySelectorAll(".question");
        var userScoreInput = document.getElementById("user-score");
    
        quizDuration = (questions.length) * 60; // convert in seconds
        
        // Update Timer
        function updateTimer() {
            var minutes = Math.floor(quizDuration / 60);
            var seconds = quizDuration % 60;
    
            timerSpan.innerText = minutes + "m" + seconds + 's';
    
            // Check if the time ended
            if (quizDuration <= 0) {
                // Automatically Submit the quiz
                clearTimeout(quizTimerId);
                submitQuiz();
            } else if (document.getElementById("message-div")) {
                clearTimeout(quizTimerId);
                highlightCorrectAnswers();
            } else {
                // decrement the timer value by 1s
                quizDuration--;
            }
        }
    
        // Function to submit the quiz
        function submitQuiz() {
            // Calculate the score
            calculateScore();
    
            // Submit the quiz
            quizForm.submit();
        }
    
        // Check right answer and then calculate the score
        function calculateScore() {
            var score = 0;
    
            // Loop through each question
            questions.forEach(question => {
                var selectedInput = question.querySelector('input:checked');
                var correctAnswer = question.querySelector(".correct-answer").innerText;
    
                // Check if the answer is correct or not
                if (selectedInput && selectedInput.value === correctAnswer) {
                    score += 1;
                }
            });
    
            // Update the hidden input field with score in form
            userScoreInput.value = score;
        }
    
        // highlight correct answer while showing result
        function highlightCorrectAnswers() {
            questions.forEach(question => {
                var correctAnswer = question.querySelector(".correct-answer");
                correctAnswer.previousElementSibling.querySelector("input").classList.add("bg-success");
                correctAnswer.previousElementSibling.classList.add("fw-bold");
            });
    
            // disable submit button
            submitButton.disabled = true;
    
            // disabel all options
            var options = document.querySelectorAll(".form-check-input");
            options.forEach(option => {
                option.disabled = true;
            });
        }
    
        // Attach Event Listener to Submit button
        submitButton.addEventListener("click", submitQuiz);
    
        // Timer Interval
        quizTimerId = setInterval(updateTimer, 1000);
    </script>


   {% endblock content %}

templates/register.html
{% extends 'index.html' %}

{% block title %} Register Page - BrainStrom{% endblock title %}

{% block content %}

      <h1 class="text-center display-4 my-5">Register</h1>

      <div class="container">
        <div class="row row-cols-sm-1 row-cols-lg-3 container">
            <div class="col-12">
              </div>
              <div class="col-12">

                <div>
                  {% if messages %}
                    <ul class="messages">
                     {% for message in messages %}
                        <li>{{ message }}</li>
                     {% endfor %}
                   </ul>
                  {% endif %}
                </div>

                <form method="POST" action="">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label for="exampleInputEmail2" class="form-label visually-hidden">Email</label>
                    <input type="email" name="email" class="form-control" id="exampleInputEmail2" aria-describedby="emailHelp" placeholder="Email" required>
                  </div>
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label visually-hidden">Username</label>
                      <input type="username" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username" required>
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label visually-hidden">Password</label>
                      <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword2" class="form-label visually-hidden">Repeat Password</label>
                      <input type="password" name="password2" class="form-control" id="exampleInputPassword2" placeholder="Repeat Password" required>
                    </div>
                    <div class="mb-3 form-check">
                      <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                      <label class="form-check-label" for="exampleCheck1">Terms and Conditions</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Register</button>
                    <p>Already a user?<a href="{% url 'login' %}">Login</a></p>
                  </form>
              </div>
              <div class="col-12">
              </div>
      </div>

{% endblock content %}